title: ""
email: ""
description: ""
baseurl: ""
url: "https://GrahamSH-LLK.github.io"

source: site
markdown: kramdown

plugins:
- jekyll-autoprefixer
- jekyll-minifier
<<<<<<< HEAD
- jekyll-last-modified-at

=======
>>>>>>> parent of 3498e1b... Update _config.yml

autoprefixer:
  browsers:
  - ">= 1%"
  - last 1 major version
  - not dead
  - Chrome >= 60
  - Firefox >= 60
  - Edge >= 16
  - iOS >= 10
  - Safari >= 10
  - Android >= 6
  - not Explorer <= 11

jekyll-minifier:
  uglifier_args:
    harmony: true
